### ISSUE TITLE
LIDE-003: Create a base testing framework

### ISSUE THREAD

**Issue by hark130** [globalinfotek/linux-dev-practice#3]
Add/create a basic testing framework necessary to provide immediate feedback on practice results.

**Comment by suirad** [comment]
Is there a specific desired framework for testing?

**Comment by hark130** [comment]
> Is there a specific desired framework for testing?

I already have a [framework](https://github.com/hark130/tedious-start) that utilizes Python's unittest module.  I just need to provision the CDE with the wheel and ensure it all still works.

I'll be able to tweak/extend the framework even more once I start writing my first "exercise".

**Comment by hark130** [comment]
Merge request is [here](https://github.com/globalinfotek/linux-dev-practice/pull/7)
